dist: trusty
sudo: required

matrix:
    include:
        - env: TARGET=rc2014
        - env: TARGET=trs80
        - env: TARGET=z80pack
        - env: TARGET=dragon-nx32
        - env: TARGET=v65c816

before_install:
    - sudo add-apt-repository -y ppa:p-pisati/fuzix
    - sudo apt-get update -q
    - sudo apt-get install -y byacc automake			# FUZIX build deps
    - sudo apt-get install -y sdcc						# z80pack build deps
    - sudo apt-get install -y lwtools gcc6809			# dragon-nx32 build deps
    - sudo update-alternatives --set yacc /usr/bin/byacc

language: c

script:
    - FUZIX_CCOPTS=-O0 make TARGET=$TARGET -j2
